---
project_name: hetzner-k3s
before:
  hooks:
    - go mod download
builds:
  - main: ./cmd/hetzner-k3s/main.go
    env:
      - CGO_ENABLED=0
    ldflags:
      - "-s -w -X 'hetzner-k3s/cmd/commands.Version={{ .Tag }}'"
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - arm64
      - amd64
      - "386"
    ignore:
      - goos: windows
        goarch: arm64
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip
    name_template: '{{- .ProjectName -}}_{{- .Os -}}_{{- if and (eq .Os "Linux") (eq .Arch "arm64") -}}aarch64{{- else -}}{{- .Arch -}}{{- end -}}'
    files:
      - none*
checksum:
  name_template: 'checksums.txt'
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
nfpms:
  - package_name: hetzner-k3s
    file_name_template: '{{- .ProjectName -}}_{{- .Os -}}_{{- if and (eq .Os "Linux") (eq .Arch "arm64") -}}aarch64{{- else -}}{{- .Arch -}}{{- end -}}'
    replacements:
      darwin: Darwin
      linux: Linux
      386: i386
      amd64: x86_64
    maintainer: Janos Miko <info@janosmiko.com>
    description: This is a CLI tool to quickly create and manage Kubernetes clusters in Hetzner Cloud using the lightweight Kubernetes distribution k3s from Rancher.
    license: MIT
    formats:
      - deb
      - rpm
    dependencies: []
    recommends: []
    bindir: /usr/bin
    contents: [ ]
    rpm:
      compression: lzma
brews:
  - tap:
      owner: janosmiko
      name: homebrew-tap
      token: "{{ .Env.GITHUB_TOKEN }}"
    commit_author:
      name: Janos Miko
      email: info@janosmiko.com
    folder: Formula
    description: This is a CLI tool to quickly create and manage Kubernetes clusters in Hetzner Cloud using the lightweight Kubernetes distribution k3s from Rancher.
    license: MIT
    skip_upload: "false"
    dependencies:
      - name: kubectl
        type: required
